# Generated by Django 2.2.5 on 2021-05-16 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_song_podcast_audio', models.CharField(blank=True, max_length=100, unique=True)),
                ('duration', models.PositiveIntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=10)),
                ('title_of_audiobook', models.CharField(blank=True, max_length=100, null=True)),
                ('author_of_title', models.CharField(blank=True, max_length=100, null=True)),
                ('narrator', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_type', models.CharField(choices=[('song', 'Song'), ('podcast', 'Podcast'), ('audiobook', 'Audiobook')], default=None, max_length=30)),
            ],
            options={
                'db_table': 'media_uploads',
            },
        ),
    ]
