# Generated by Django 2.2.5 on 2021-05-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='name_song_podcast_audio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
